import Head from 'next/head'
import Header from '../../modules/dashboard/header'
import Sidebar from '../../modules/dashboard/sidebar'
import {useEffect, useState} from 'react'
import {supabase} from '../../utils/supabaseClient'
import { TbPlugConnected } from 'react-icons/tb'
import ConnectChannel from '../../modules/dashboard/connectchannel'

export default function Connect() {
  const [loading, setLoading] = useState(true)
  const [username, setUsername] = useState(null)
  const [first_name, setFirstName] = useState(null)
  const [last_name, setLastName] = useState(null)
  const [email, setEmail] = useState(null)
  const [bio, setBio] = useState(null)
  const [website, setWebsite] = useState(null)
  const [avatar_url, setAvatarUrl] = useState(null)
  const [checked, setChecked] = useState(false)

  useEffect(() => {
    getProfile()
  }, [])

  async function getProfile() {
    try {
      setLoading(true)
      const user = supabase.auth.user()

      let {data, error, status} = await supabase
        .from('profiles')
        .select(
          `username, first_name, last_name, bio, email, website, avatar_url`
        )
        .eq('id', user.id)
        .single()

      if (error && status !== 406) {
        throw error
      }

      if (data) {
        setUsername(data.username)
        setFirstName(data.first_name)
        setLastName(data.last_name)
        setEmail(data.email)
        setBio(data.bio)
        setWebsite(data.website)
        setAvatarUrl(data.avatar_url)
      }
    } catch (error) {
      console.error(error.message)
    } finally {
      setLoading(false)
    }
  }

  async function updateProfile({
    username,
    first_name,
    last_name,
    email,
    bio,
    website,
    avatar_url,
  }) {
    try {
      setLoading(true)
      const user = supabase.auth.user()

      const updates = {
        id: user.id,
        username,
        first_name,
        last_name,
        email,
        bio,
        website,
        avatar_url,
        updated_at: new Date(),
      }

      let {error} = await supabase.from('profiles').upsert(updates, {
        returning: 'minimal', // Don't return the value after inserting
      })

      if (error) {
        throw error
      }
    } catch (error) {
      console.error(error.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className='h-screen overflow-x-hidden'>
      <Head>
        <title>Menetrend - Connect</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex bg-gray-200 dark:bg-gray-900 h-screen overflow-hidden text-background dark:text-white'>
        <Header />
        <Sidebar />
        <div className='mt-24 ml-8 mr-8 w-full'>
          <div className='text-3xl font-bold flex items-center space-x-2'>
            <div className='bg-gray-300 dark:bg-gray-700 h-10 w-10 flex justify-center items-center rounded-md text-gray-700 dark:text-white'>
              <TbPlugConnected />
            </div>
            <div>Connect</div>
          </div>
          <div className='space-y-6 pt-12'>
            <div className='flex pb-12'>
              <div className=''>
                <div className='text-2xl font-bold'>Connect a new Channel</div>
                <div className='text-sm font-medium text-gray-600 dark:text-gray-400'>
                  Select the channel you want to use.
                </div>
              </div>
            </div>
            <div className='grid pb-12'>
              <ConnectChannel />
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  }
}
