import Head from 'next/head'
import Image from 'next/image'
import Header from '../../modules/homepage/header'
import Footer from '../../modules/homepage/footer'
import HeaderBanner from '../../components/headerbanner'

import heroImg from '../../public/heroImg.png'

export default function AutomateYourMarketing() {
  return (
    <div className='h-screen'>
      <Head>
        <title>Menetrend - Social Media Management for Indie Hackers</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main className='block bg-gray-900 px-52 text-white content-center pt-20'>
        <div className='grid space-y-5 text-center pt-32'>
          <span className='text-lg font-bold text-purple-700'>
            FOR ENTREPRENEURS
          </span>
          <span className='text-6xl font-black'>
            Automate your marketing
            <a className='text-transparent bg-clip-text bg-gradient-to-br from-menetrend-blue to-menetrend-pink'>
              .
            </a>
          </span>
          <span className='font-normal text-lg'>
            Create hands-free automated workflows that take care of repetitive
            marketing tasks in the background while you focus on what matters
            most
          </span>
        </div>
        <div>
            <Image src={heroImg} layout='responsive'/>
        </div>
      </main>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      protected: false,
    },
  }
}
