import Head from 'next/head'
import Header from '../modules/homepage/header'
import Footer from '../modules/homepage/footer'
import HeaderBanner from '../components/headerbanner'

export default function Blog() {
  return (
    <div className='h-screen'>
      <Head>
        <title>Menetrend - Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      {/* <HeaderBanner /> */}
      <main className='block bg-gray-900 text-white pt-52 h-[700px] px-52 text-background content-center'>
        <div className='text-white flex justify-between'>
          <div className='bg-gray-500 rounded-md border-2 border-indigo-600 flex justify-center items-center aspect-video w-5/12'>
            IMAGE PLACEHOLDER
          </div>
          <div className='w-6/12 space-y-8'>
            <div className='grid space-y-4'>
              <span className='text-sm font-medium text-gray-400'>
                26. March 2022 • 6 minute read
              </span>
              <span className='text-3xl font-bold'>
                Get started with Menetrend - Be where your customers are
              </span>
              <span>
                Menetrend is a service used by entrepreneurs and small
                businesses who want to generate more customers through social
                media. We create custom, native content for instagram, schedule
                it or post it in real-time. We handle it all, from strategy to
                results.
              </span>
            </div>
            <div className='flex space-x-4'>
              <div className='h-12 w-12 bg-gray-300 rounded-full'></div>
              <div className='grid'>
                <span className='font-semibold text-lg'>Christian Lutz</span>
                <span className='font-thin text-sm text-gray-300'>
                  Founder and CTO
                </span>
              </div>
            </div>
          </div>
        </div>
      </main>
      <div className='py-8 px-52 pt-32 bg-white text-gray-900 space-y-32'>
        <div className='text-white flex justify-between'>
          <div className='bg-gray-500 rounded-md border-2 border-indigo-600 flex justify-center items-center aspect-video w-5/12'>
            IMAGE PLACEHOLDER
          </div>
          <div className='w-6/12 space-y-8 text-gray-900'>
            <div className='grid space-y-4'>
              <span className='text-sm font-medium text-gray-400'>
                26. March 2022 • 6 minute read
              </span>
              <span className='text-3xl font-bold text-gray-900'>
                Get started with Menetrend - Be where your customers are
              </span>
              <span>
                Menetrend is a service used by entrepreneurs and small
                businesses who want to generate more customers through social
                media. We create custom, native content for instagram, schedule
                it or post it in real-time. We handle it all, from strategy to
                results.
              </span>
            </div>
            <div className='flex space-x-4'>
              <div className='h-12 w-12 bg-gray-300 rounded-full'></div>
              <div className='grid'>
                <span className='font-semibold text-lg'>Christian Lutz</span>
                <span className='font-thin text-sm text-gray-300'>
                  Founder and CTO
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      protected: false,
    },
  }
}
