import Head from 'next/head'
import Header from '../modules/homepage/header'
import Footer from '../modules/homepage/footer'
import HeaderBanner from '../components/headerbanner'

export default function Features() {
  return (
    <div className='h-screen'>
      <Head>
        <title>Menetrend - Social Media Management for Indie Hackers</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <HeaderBanner />
      <main className='block bg-white h-5/6 px-52 text-background content-center pt-20'>
        Test
      </main>
      <div className='py-8 px-52 pt-32 space-y-32'></div>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      protected: false,
    },
  }
}
