import Head from 'next/head'
import Header from '../../modules/dashboard/header'
import Sidebar from '../../modules/dashboard/sidebar'
import Script from 'next/script'
import {BiCalendar} from 'react-icons/bi'
import React, {useEffect, useState, Fragment} from 'react'
import ScheduleComponent from '../../components/schedulecomponent'
import {Combobox, Transition} from '@headlessui/react'
import {CheckIcon, SelectorIcon} from '@heroicons/react/solid'
import {Listbox} from '@headlessui/react'
import AddSchedule from '../../modules/dashboard/addschedule'



export default function Calendar() {

  return (
    <div className='h-screen w-screen overflow-x-hidden dark:text-white text-background'>
      <Head>
        <title>Menetrend - Calendar</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex bg-gray-200 dark:bg-gray-900 h-screen overflow-hidden '>
        <Header />
        <Sidebar />
        <div className='mt-24 ml-8 mr-8 w-screen '>
          <div className='text-3xl font-bold flex items-center space-x-2'>
            <div>Schedule</div>
          </div>
          <AddSchedule />
          <div className='grid mt-12 space-y-2 hover:overflow-y-scroll max-h-[600px]'>
            <ScheduleComponent />
          </div>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  }
}
