import Head from 'next/head'
import Header from '../../modules/dashboard/header'
import Sidebar from '../../modules/dashboard/sidebar'
import Script from 'next/script'
import {BiCalendar} from 'react-icons/bi'
import React from 'react'
import {IoFileTrayStacked} from 'react-icons/io5'
import {supabase} from '../../utils/supabaseClient'
import {useState, useEffect} from 'react'
import {Identity} from '@mui/base'
import Image from 'next/image'
import DraftObjects from '../../components/draftobjects'

export default function Draft() {
  const [drafts, setDrafts] = useState([])

  useEffect(() => {
    getDrafts()
  }, [])

  async function getDrafts() {
    try {
      const user = supabase.auth.user()
      const {data, error, status} = await supabase
        .from('igcontent')
        .select(
          `id, draft_id, uid, images, description, is_scheduled, schedule, created_at`
        )
        .eq('uid', user.id)
      if (error && status !== 406) {
        throw error
      }
      if (data) {
        setDrafts(data)
      }
    } catch (error) {
      console.log(error.message)
    }
  }

  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Menetrend - Draft</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex bg-gray-200 dark:bg-gray-900 h-screen overflow-hidden text-background dark:text-white'>
        <Header />
        <Sidebar />
        <div className='mt-24 ml-8 mr-8 w-2/3'>
          <div className='text-3xl font-bold flex items-center space-x-2'>
            <div className='bg-gray-300 dark:bg-gray-700 h-10 w-10 justify-center flex items-center rounded-md text-gray-700'>
              <IoFileTrayStacked className='dark:text-white' />
            </div>
            <span>Draft</span>
          </div>
          <div className='mt-24 mr-8 w-full text-background flex space-x-2 blur-sm'>
            <DraftObjects drafts={drafts} />
          </div>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  }
}
