import Head from 'next/head'
import Header from '../../modules/dashboard/header'
import Sidebar from '../../modules/dashboard/sidebar'
import {BiEdit} from 'react-icons/bi'
import InstagramPreview from '../../modules/dashboard/instagrampreview'
import MenetrendInput from '../../components/menetrendinput'
import {useState, useEffect} from 'react'
import ImageUploader from '../../modules/dashboard/imageuploader'
import Button from '../../components/button'
import {supabase} from '../../utils/supabaseClient'
import DraftObjects from '../../components/draftobjects'
import Image from 'next/image'

export default function Home() {
  const [description, setDescription] = useState('')
  const [parentImages, setParentImages] = useState([])
  const [containerID, setContainerID] = useState([])
  const [first_name, setFirstName] = useState(null)
  const [last_name, setLastName] = useState(null)
  const [avatar_url, setAvatarUrl] = useState(null)
  const [loading, setLoading] = useState(false)
  const [drafts, setDrafts] = useState([])

  useEffect(() => {
    getProfile()
  }, [])

  async function getProfile() {
    try {
      setLoading(true)
      const user = supabase.auth.user()

      let {data, error, status} = await supabase
        .from('profiles')
        .select(
          `username, first_name, last_name, bio, email, website, avatar_url`
        )
        .eq('id', user.id)
        .single()

      if (error && status !== 406) {
        throw error
      }

      if (data) {
        setFirstName(data.first_name)
        setLastName(data.last_name)
        setAvatarUrl(data.avatar_url)
      }
    } catch (error) {
      console.error(error.message)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    getDrafts()
  }, [])

  async function getDrafts() {
    try {
      const user = supabase.auth.user()
      const {data, error, status} = await supabase
        .from('igcontent')
        .select(
          `id, draft_id, uid, images, description, is_scheduled, schedule, created_at`
        )
        .eq('uid', user.id)
      if (error && status !== 406) {
        throw error
      }
      if (data) {
        setDrafts(data)
      }
    } catch (error) {
      //console.log(error.message)
    }
  }

  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Menetrend - Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex bg-gray-200 dark:bg-gray-900 h-screen overflow-hidden text-background dark:text-white'>
        <Header />
        <Sidebar />
        <div className='mt-24 ml-8 mr-8 w-2/3 text-background dark:text-white'>
          <div className='text-3xl font-bold items-center'>
            <div>Good evening, {first_name}. 👋</div>
            <span className='text-xl text-indigo-400'>This feature is coming soon!</span>
          </div>
          <div className='pt-12 space-y-4 blur-sm'>
            <div className='bg-white dark:bg-gray-800 rounded-md shadow-md p-4 w-[800px] space-y-4'>
              <span className='text-xl font-semibold'>
                5 posts are scheduled this week.
              </span>
              <div>
                <table className='w-full text-sm text-left text-gray-500 dark:text-gray-400'>
                  <thead className='text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400'>
                    <tr>
                      <th scope='col' className='px-6 py-3'>
                        Image
                      </th>
                      <th scope='col' className='px-6 py-3'>
                        Description
                      </th>
                      <th scope='col' className='px-6 py-3'>
                        Schedule
                      </th>
                      <th scope='col' className='px-6 py-3'>
                        <span className='sr-only'>Edit</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600'>
                      <th
                        scope='row'
                        className='px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap'>
                        IMG
                      </th>
                      <td className='px-6 py-4'>Sliver</td>
                      <td className='px-6 py-4'>Laptop</td>
                      <td className='px-6 py-4 text-right'>
                        <a
                          href='#'
                          className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                          Edit
                        </a>
                      </td>
                    </tr>
                    <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600'>
                      <th
                        scope='row'
                        className='px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap'>
                        Microsoft Surface Pro
                      </th>
                      <td className='px-6 py-4'>White</td>
                      <td className='px-6 py-4'>Laptop PC</td>
                      <td className='px-6 py-4 text-right'>
                        <a
                          href='#'
                          className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                          Edit
                        </a>
                      </td>
                    </tr>
                    <tr className='bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-600'>
                      <th
                        scope='row'
                        className='px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap'>
                        Magic Mouse 2
                      </th>
                      <td className='px-6 py-4'>Black</td>
                      <td className='px-6 py-4'>Accessories</td>
                      <td className='px-6 py-4 text-right'>
                        <a
                          href='#'
                          className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                          Edit
                        </a>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div className='bg-white dark:bg-gray-800 rounded-md shadow-md p-4 w-[800px] space-y-4'>
              <span className='text-xl font-semibold'>
                5 posts are scheduled this week.
              </span>
              <div>
                <table className='w-full text-sm text-left text-gray-500 dark:text-gray-400'>
                  <thead className='text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400'>
                    <tr>
                      <th scope='col' className='px-6 py-3'>
                        Image
                      </th>
                      <th scope='col' className='px-6 py-3'>
                        Description
                      </th>
                      <th scope='col' className='px-6 py-3'>
                        Schedule
                      </th>
                      <th scope='col' className='px-6 py-3'>
                        <span className='sr-only'>Edit</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600'>
                      <th
                        scope='row'
                        className='px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap'>
                        IMG
                      </th>
                      <td className='px-6 py-4'>Sliver</td>
                      <td className='px-6 py-4'>in 20 minutes</td>
                      <td className='px-6 py-4 text-right'>
                        <a
                          href='#'
                          className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                          Edit
                        </a>
                      </td>
                    </tr>
                    <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600'>
                      <th
                        scope='row'
                        className='px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap'>
                        Microsoft Surface Pro
                      </th>
                      <td className='px-6 py-4'>White</td>
                      <td className='px-6 py-4'>Tomorrow at 18:00</td>
                      <td className='px-6 py-4 text-right'>
                        <a
                          href='#'
                          className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                          Edit
                        </a>
                      </td>
                    </tr>
                    <tr className='bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-600'>
                      <th
                        scope='row'
                        className='px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap'>
                        Magic Mouse 2
                      </th>
                      <td className='px-6 py-4'>Black</td>
                      <td className='px-6 py-4'>Thursday at 20:00</td>
                      <td className='px-6 py-4 text-right'>
                        <a
                          href='#'
                          className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                          Edit
                        </a>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  }
}
